config/routes.rb
Final::Application.routes.draw do
  resources :advertisments

  resources :nutrition_clients

  resources :clients

  

  get "home/index"

  get "home/welcome"
  
  get "home/weight"
  
  get "home/cardio"
  
  get "home/personal"
  
  get "home/nutrition"
  
  get "home/about"
  
  get "home/contact"
  
  get "services/nutrition1"
  
  get "services/personal1"

  root :to => 'home#index'

end

app/models/advertisment.rb
class Advertisment < ActiveRecord::Base
	attr_accessible :title, :descritption, :image_path, :start_date, :end_date
	validates :title, presence: true
	validates :descritption, presence: true
	validates :image_path, presence: true
	validates :start_date, presence: true
	validates :end_date, presence:true

end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to	:nutrition_clients	
end

app/models/nutrition_client.rb
class NutritionClient < ActiveRecord::Base	
	
end

app/controllers/advertisments_controller.rb
class AdvertismentsController < ApplicationController
  # GET /advertisments
  # GET /advertisments.json
  def index
    @advertisments = Advertisment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @advertisments }
    end
  end

  # GET /advertisments/1
  # GET /advertisments/1.json
  def show
    @advertisment = Advertisment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advertisment }
    end
  end

  # GET /advertisments/new
  # GET /advertisments/new.json
  def new
    @advertisment = Advertisment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advertisment }
    end
  end

  # GET /advertisments/1/edit
  def edit
    @advertisment = Advertisment.find(params[:id])
  end

  # POST /advertisments
  # POST /advertisments.json
  def create
    @advertisment = Advertisment.new(params[:advertisment])

    respond_to do |format|
      if @advertisment.save
        format.html { redirect_to @advertisment, notice: 'Advertisment was successfully created.' }
        format.json { render json: @advertisment, status: :created, location: @advertisment }
      else
        format.html { render action: "new" }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /advertisments/1
  # PUT /advertisments/1.json
  def update
    @advertisment = Advertisment.find(params[:id])

    respond_to do |format|
      if @advertisment.update_attributes(params[:advertisment])
        format.html { redirect_to @advertisment, notice: 'Advertisment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisments/1
  # DELETE /advertisments/1.json
  def destroy
    @advertisment = Advertisment.find(params[:id])
    @advertisment.destroy

    respond_to do |format|
      format.html { redirect_to advertisments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	  
  end

  def welcome
  	  @advertismentlist=Advertisment.all
  end
  
  def weight
  end
  
  def cardio
  end
  
  def personal
  end
  
  def nutrition
  end
  
  def about
  end
  
  def contact
  end
  
  def nutrition1
  end
  
  def personal1
  end
  	  
  	  
end

app/controllers/nutrition_clients_controller.rb
class NutritionClientsController < ApplicationController
  # GET /nutrition_clients
  # GET /nutrition_clients.json
  def index
    @nutrition_clients = NutritionClient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nutrition_clients }
    end
  end

  # GET /nutrition_clients/1
  # GET /nutrition_clients/1.json
  def show
    @nutrition_client = NutritionClient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nutrition_client }
    end
  end

  # GET /nutrition_clients/new
  # GET /nutrition_clients/new.json
  def new
    @nutrition_client = NutritionClient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nutrition_client }
    end
  end

  # GET /nutrition_clients/1/edit
  def edit
    @nutrition_client = NutritionClient.find(params[:id])
  end

  # POST /nutrition_clients
  # POST /nutrition_clients.json
  def create
    @nutrition_client = NutritionClient.new(params[:nutrition_client])

    respond_to do |format|
      if @nutrition_client.save
        format.html { redirect_to @nutrition_client, notice: 'Nutrition client was successfully created.' }
        format.json { render json: @nutrition_client, status: :created, location: @nutrition_client }
      else
        format.html { render action: "new" }
        format.json { render json: @nutrition_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nutrition_clients/1
  # PUT /nutrition_clients/1.json
  def update
    @nutrition_client = NutritionClient.find(params[:id])

    respond_to do |format|
      if @nutrition_client.update_attributes(params[:nutrition_client])
        format.html { redirect_to @nutrition_client, notice: 'Nutrition client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nutrition_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutrition_clients/1
  # DELETE /nutrition_clients/1.json
  def destroy
    @nutrition_client = NutritionClient.find(params[:id])
    @nutrition_client.destroy

    respond_to do |format|
      format.html { redirect_to nutrition_clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	http_basic_authenticate_with :name=>"nserafin", :password=>"yoyoyo123@"
	
	def personal1
	end
	
	def nutrition1
	end
end

app/helpers/advertisments_helper.rb
module AdvertismentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nutrition_clients_helper.rb
module NutritionClientsHelper
	
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/advertisments/_form.html.erb
<%= form_for(@advertisment) do |f| %>
  <% if @advertisment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertisment.errors.count, "error") %> prohibited this advertisment from being saved:</h2>

      <ul>
      <% @advertisment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :descritption %><br />
    <%= f.text_area :descritption %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br />
    <%= f.text_field :image_path %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertisments/edit.html.erb
<h1>Editing advertisment</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertisment %> |
<%= link_to 'Back', advertisments_path %>

app/views/advertisments/index.html.erb
<h1>Listing advertisments</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Descritption</th>
    <th>Image path</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @advertisments.each do |advertisment| %>
  <tr>
    <td><%= advertisment.title %></td>
    <td><%= advertisment.descritption %></td>
    <td><%= advertisment.image_path %></td>
    <td><%= advertisment.start_date %></td>
    <td><%= advertisment.end_date %></td>
    <td><%= link_to 'Show', advertisment %></td>
    <td><%= link_to 'Edit', edit_advertisment_path(advertisment) %></td>
    <td><%= link_to 'Destroy', advertisment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Advertisment', new_advertisment_path %>

app/views/advertisments/new.html.erb
<h1>New advertisment</h1>

<%= render 'form' %>

<%= link_to 'Back', advertisments_path %>

app/views/advertisments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @advertisment.title %>
</p>

<p>
  <b>Descritption:</b>
  <%= @advertisment.descritption %>
</p>

<p>
  <b>Image path:</b>
  <%= @advertisment.image_path %>
</p>

<p>
  <b>Start date:</b>
  <%= @advertisment.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @advertisment.end_date %>
</p>


<%= link_to 'Edit', edit_advertisment_path(@advertisment) %> |
<%= link_to 'Back', advertisments_path %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<%=link_to "Home", home_welcome_path%></br>
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Activitylevel</th>
    <th>Joindate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.FirstName %></td>
    <td><%= client.LastName %></td>
    <td><%= client.Height %></td>
    <td><%= client.Weight %></td>
    <td><%= client.ActivityLevel %></td>
    <td><%= client.JoinDate %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %></br></br></br></br>

<%=link_to "Personal Training Plan", services_personal1_path%>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @client.FirstName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @client.LastName %>
</p>

<p>
  <b>Height:</b>
  <%= @client.Height %>
</p>

<p>
  <b>Weight:</b>
  <%= @client.Weight %>
</p>

<p>
  <b>Activitylevel:</b>
  <%= @client.ActivityLevel %>
</p>

<p>
  <b>Joindate:</b>
  <%= @client.JoinDate %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/cardio.html.erb
<html>
<body>
	<h1>Cardiovascular Training Equipment</h1>
	<table>
 
	<td><p><%=link_to "Home", home_welcome_path%></p></td>  
	<td><p><%=link_to "Weight Training Equipment", home_weight_path%></p></td>
	<td><p><%=link_to "Cardiovascular Training Equipment", home_cardio_path%></p></td> 
	<td><p><%=link_to "Personal Training", home_personal_path%></p></td> 
	<td><p><%=link_to "Nutrition", home_nutrition_path%></p></td> 
	<td><p><%=link_to "Contact Us", home_contact_path%></p></td>  
	<h1>keep it up</h1>


	</table>
	
	
	<p>Choose from the great selection of cardiovascular training equipment and when you are ready to purchase please call this number: 708-307-6995</p>
	
	<table>
	<tr>
	
	<td><%=image_tag("cardio1.jpg")%>
	<p>Elliptical</p>
	<p>This machine is a great for an all around cardio workout.</p></td>
	<td><%=image_tag("cardio2.jpg")%>
	<p>Hybrid Elliptical</p>
	<p>This machine incorporates a tredmill and an elliptical for a greater workout.</p></td>
	</tr>
	<tr>
	<td><%=image_tag("cardio3.jpg")%>
	<p>Bike</p>
	<p>This machine is a classic for a great cardio workout</p></td>
	<td><%=image_tag("cardio4.jpg")%>
	<p>Tredmill</p>
	<p>This machine is great for a working on your cardiovascular health</p></td>
	</tr>
	</table>
</body>
</html>
	

app/views/home/contact.html.erb
<html>
<body>
<h1>Contact Us</h1>
<table>

	<td><p><%=link_to "Home", home_welcome_path%></p></td>  
	<td><p><%=link_to "Weight Training Equipment", home_weight_path%></p></td>
	<td><p><%=link_to "Cardiovascular Training Equipment", home_cardio_path%></p></td> 
	<td><p><%=link_to "Personal Training", home_personal_path%></p></td> 
	<td><p><%=link_to "Nutrition", home_nutrition_path%></p></td> 
	<td><p><%=link_to "Contact Us", home_contact_path%></p></td>  
	


</table>
<p>If you have any problems with the site or our services you can contact us with email or by calling us.</p>
<p>E-mail:ficknation@gmail.com</p>
<p>Phone:708-307-6995</p>
<p>Thank you very much for your visit and I cannot wait to hear from you if you have any concerns!</p>

<%=image_tag("jump.jpg")%>
</body>
</html>

app/views/home/index.html.erb
<html>
<body>
<h1> Welcome to Serafin Fitness</h1></br>

<p>The one stop shop for all your fitness needs and goals</p></br>

<%=image_tag("Fitness.jpg")%></br>

<p><%=link_to "Click Here To Enter Site", home_welcome_path%></p></td>


</body>
</html> 

app/views/home/nutrition.html.erb
<html>
<body>
<h1>Nutrition Coaching</h1>
<table>

	<td><p><%=link_to "Home", home_welcome_path%></p></td>  
	<td><p><%=link_to "Weight Training Equipment", home_weight_path%></p></td>
	<td><p><%=link_to "Cardiovascular Training Equipment", home_cardio_path%></p></td> 
	<td><p><%=link_to "Personal Training", home_personal_path%></p></td> 
	<td><p><%=link_to "Nutrition", home_nutrition_path%></p></td> 
	<td><p><%=link_to "Contact Us", home_contact_path%></p></td>  
	


</table>
<p>Nutrition is the one part of fitness that many people forget about.  You can do a great deal of work in the gym but if you are not
on top of your nutrition your results will be lacking</p>
<p>Signing up for our nutrition services will give you a meal plan to use that will make your transformation goals possible.</p>
<p>Simply Click the Link below and fillout some information about yourself. Once the form is completed you will be contacted with an amount for the services and your login information to see your new nutrition plan

	<p><%=link_to "Nutrition Sign Up", nutrition_clients_path%></p></td>
	
	<%=image_tag("food.jpg")%>

app/views/home/nutrition1.html.erb
<html>
<body>
<h1>Nutrition Plan</h1>
<p><%=link_to "Home", home_welcome_path%></p>
<p>This plan can be used for everyday of the week and will fit your needs based on your caloric needs</p>
<h2>Breakfast</h2>
<p>3 whole eggs, 1 pancake, 8oz of orange juice</p>
<h3>Snack</h3>
<p>Protein shake</p>
<h4>Lunch</h4>
<p>Chicken sandwhich, brown rice, and water</p>
<h5>Snack</h5>
<p>Protein shake</p>
<h6>Dinner</h6>
<p>Chicken, pasta, and water</p>

app/views/home/personal.html.erb
<html>
<body>
<h1>Personal Training</h1>
<table>

	<td><p><%=link_to "Home", home_welcome_path%></p></td>  
	<td><p><%=link_to "Weight Training Equipment", home_weight_path%></p></td>
	<td><p><%=link_to "Cardiovascular Training Equipment", home_cardio_path%></p></td> 
	<td><p><%=link_to "Personal Training", home_personal_path%></p></td> 
	<td><p><%=link_to "Nutrition", home_nutrition_path%></p></td> 
	<td><p><%=link_to "Contact Us", home_contact_path%></p></td>  
	


</table>

<p>If you are having trouble obtaining your goals by yourself then prehaps personal training is right for you!</p>
<p>Our personal Trainers have years of experience and know exactly what program to use to transform your body into what you have always wanted.<p>
<p>Simply Click the Link below and fillout some information about yourself.  Once the form is completed you will be contacted with an amount for the services and your login information 
to see your new workout plan</p>

	<p><%=link_to "Client Sign Up", clients_path%></p></td>
	
	<%=image_tag("weight5.jpg")%>

app/views/home/personal1.html.erb
<html>
<body>
<h1>Workout Plan</h1>
<p><%=link_to "Home", home_welcome_path%></p>


<p>Mon-Chest, Shoulder, and Triceps Day</p>
<p>Tue-Rest</p>
<p>Wed-Back and Biceps Day</p>
<p>Thurs-Rest</p>
<p>Fri-Legs</p>
<p>Sat-Rest</p>
<p>Sun-Rest</p>

<h2>Chest, Shoulder, and Triceps Workout</h2>
<p>Flat Bench 3X10, Incline Bench 3X10, Chest Flys 3X10, DumbbellShoulder Press 3X10, Lateral Raises 3X10, and Rope Pull Downs 3X10</p></br>
<h3>Back and Biceps Workout</h3>
<p>Deadlift 3X10, Lat Pull Down 3X10, Cable Row 3X10, Barbell Curl 3X10, and Dumbbell Curl 3X10</p></br>
<h4>Leg Workout</h4>
<p>Squat 3X10, Leg Press 3X10, Leg Curl 3X10, Leg Extension 3X10, and Calf Raise 3X10</p> 

app/views/home/weight.html.erb
<html>
<body>
	<h1>Weight Training Equipment</h1>
	<table>

	<td><p><%=link_to "Home", home_welcome_path%></p></td>  
	<td><p><%=link_to "Weight Training Equipment", home_weight_path%></p></td>
	<td><p><%=link_to "Cardiovascular Training Equipment", home_cardio_path%></p></td> 
	<td><p><%=link_to "Personal Training", home_personal_path%></p></td> 
	<td><p><%=link_to "Nutrition", home_nutrition_path%></p></td> 
	<td><p><%=link_to "Contact Us", home_contact_path%></p></td>  
	


	</table>
	
	
	<p>Choose from the great selection of weight training equipment and when you are ready to purchase please call this number: 708-307-6995</p>
	
	<table>
	<tr>
	
	<td><%=image_tag("weight1.jpg")%>
	<p>Full Body Machine</p>
	<p>This machine is a great for an all around full body workout.</p></td>
	<td><%=image_tag("weight2.jpg")%>
	<p>Chest/Leg Machine</p>
	<p>This machine is great for chest and leg workouts</p></td>
	</tr>
	<tr>
	<td><%=image_tag("weight3.jpg")%>
	<p>Shoulder Machine</p>
	<p>This machine is great for a shoulder workout</p></td>
	<td><%=image_tag("weight4.jpg")%>
	<p>Back and Arms Machine</p>
	<p>This machine is great for a working out your backand arms</p></td>
	</tr>
	</table>
</body>
</html>
	

app/views/home/welcome.html.erb
<html>
<head>
<style>
img {height:50px; width:50px;}
</style>
</head>

<body>
<h1> Serafin Fitness</h1>
<table>

	<td><p><%=link_to "Home", home_welcome_path%></p></td>  
	<td><p><%=link_to "Weight Training Equipment", home_weight_path%></p></td>
	<td><p><%=link_to "Cardiovascular Training Equipment", home_cardio_path%></p></td> 
	<td><p><%=link_to "Personal Training", home_personal_path%></p></td> 
	<td><p><%=link_to "Nutrition", home_nutrition_path%></p></td> 
	<td><p><%=link_to "Contact Us", home_contact_path%></p></td>  
	


</table>



<p>All of your fitness needs can be accomplished at this site</p>

<p>We can provide you with the latest and top end fitness equipment</p>

<p>Also, we have elite personal trainers and nutritionists that can transform your body into what you have always wanted it to look like.</p>

<%=image_tag("jump.jpg")%></p>
<p>
		<table>
		<tr>
		 <td><strong>title</strong></td>
		 <td><strong>description</strong></td>
		 <td><strong>Image_path</strong></td>
		 <td><strong>Start_date</strong></td>
		 <td><strong>End_date</strong></td>
		</tr>
		<%@advertismentlist.each do |advertisment| %>
		<tr>
		<td><%=advertisment.title%></td>
		<td><%=advertisment.descritption%></td>
		<td><%=image_tag advertisment.image_path%></td>		
		<td><%=advertisment.start_date%></td>
		<td><%=advertisment.end_date%></td>
		</tr>
		<%end%>

	</table>
	</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nutrition_clients/edit.html.erb
<h1>Editing nutrition_client</h1>

<%= render 'form' %>

<%= link_to 'Show', @nutrition_client %> |
<%= link_to 'Back', nutrition_clients_path %>

app/views/nutrition_clients/index.html.erb
<%=link_to "Home", home_welcome_path%></br>
<h1>Listing nutrition_clients</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Dailycalories</th>
    <th>Joindate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nutrition_clients.each do |nutrition_client| %>
  <tr>
    <td><%= nutrition_client.FirstName %></td>
    <td><%= nutrition_client.LastName %></td>
    <td><%= nutrition_client.Height %></td>
    <td><%= nutrition_client.Weight %></td>
    <td><%= nutrition_client.DailyCalories %></td>
    <td><%= nutrition_client.JoinDate %></td>
    <td><%= link_to 'Show', nutrition_client %></td>
    <td><%= link_to 'Edit', edit_nutrition_client_path(nutrition_client) %></td>
    <td><%= link_to 'Destroy', nutrition_client, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nutrition client', new_nutrition_client_path %></br>
</br></br></br>


<%=link_to "Nutrition Plan", services_nutrition1_path%>

app/views/nutrition_clients/new.html.erb
<h1>New nutrition_client</h1>

<%= render 'form' %>

<%= link_to 'Back', nutrition_clients_path %>

app/views/nutrition_clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @nutrition_client.FirstName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @nutrition_client.LastName %>
</p>

<p>
  <b>Height:</b>
  <%= @nutrition_client.Height %>
</p>

<p>
  <b>Weight:</b>
  <%= @nutrition_client.Weight %>
</p>

<p>
  <b>Dailycalories:</b>
  <%= @nutrition_client.DailyCalories %>
</p>

<p>
  <b>Joindate:</b>
  <%= @nutrition_client.JoinDate %>
</p>


<%= link_to 'Edit', edit_nutrition_client_path(@nutrition_client) %> |
<%= link_to 'Back', nutrition_clients_path %>

app/views/services/nutrition1.html.erb
<html>
<body>
<h1>Nutrition Plan</h1>
<p><%=link_to "Home", home_welcome_path%></p>
<p>This plan can be used for everyday of the week and will fit your needs based on your caloric needs</p>
<h2>Breakfast</h2>
<p>3 whole eggs, 1 pancake, 8oz of orange juice</p>
<h3>Snack</h3>
<p>Protein shake</p>
<h4>Lunch</h4>
<p>Chicken sandwhich, brown rice, and water</p>
<h5>Snack</h5>
<p>Protein shake</p>
<h6>Dinner</h6>
<p>Chicken, pasta, and water</p>

app/views/services/personal1.html.erb
<html>
<body>
<h1>Workout Plan</h1>
<p><%=link_to "Home", home_welcome_path%></p>


<p>Mon-Chest, Shoulder, and Triceps Day</p>
<p>Tue-Rest</p>
<p>Wed-Back and Biceps Day</p>
<p>Thurs-Rest</p>
<p>Fri-Legs</p>
<p>Sat-Rest</p>
<p>Sun-Rest</p>

<h2>Chest, Shoulder, and Triceps Workout</h2>
<p>Flat Bench 3X10, Incline Bench 3X10, Chest Flys 3X10, DumbbellShoulder Press 3X10, Lateral Raises 3X10, and Rope Pull Downs 3X10</p></br>
<h3>Back and Biceps Workout</h3>
<p>Deadlift 3X10, Lat Pull Down 3X10, Cable Row 3X10, Barbell Curl 3X10, and Dumbbell Curl 3X10</p></br>
<h4>Leg Workout</h4>
<p>Squat 3X10, Leg Press 3X10, Leg Curl 3X10, Leg Extension 3X10, and Calf Raise 3X10</p> 